In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("data/MultipleLinearRegression.csv")
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [3]:
x1 = data.drop("GPA",axis=1)
y = data["GPA"]

In [4]:
model = LinearRegression()
model.fit(x1,y)

LinearRegression()

In [5]:
model.coef_,model.intercept_

(array([ 0.00165354, -0.00826982]), 0.29603261264909486)

In [6]:
model.score(x1,y)

0.40668119528142843

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [12]:
x1.shape

(84, 2)

In [10]:
r2 = model.score(x1,y)

n = x1.shape[0]
p = x1.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134023

In [15]:
def adj_r2(x,y):
    r2 = model.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [16]:
adj_r2(x1,y)

0.39203134825134023

In [17]:
from sklearn.feature_selection import f_regression

In [19]:
f_regression(x1,y) # The second is p-value

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [21]:
p_values = f_regression(x1,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [22]:
p_values.round(3)

array([0.   , 0.676])

In [25]:
model_summary = pd.DataFrame(data=x1.columns.values,columns=["Features"])
model_summary

Features
0         SAT
1  Rand 1,2,3

In [27]:
model_summary["Coefficient"] = model.coef_
model_summary["P-Value"] = p_values.round(3)

In [28]:
model_summary

Features  Coefficient  P-Value
0         SAT     0.001654    0.000
1  Rand 1,2,3    -0.008270    0.676